export enum UserReducerEnum {
  FOLLOW = 'SOCIAL_NETWORK/USERS/FOLLOW',
  UNFOLLOW = 'SOCIAL_NETWORK/USERS/UNFOLLOW',
  SET_USERS = 'SOCIAL_NETWORK/USERS/SET_USERS',
  SET_CURRENT_PAGE = 'SOCIAL_NETWORK/USERS/SET-CURRENT-PAGE',
  SET_TOTAL_USERS_COUNT = 'SOCIAL_NETWORK/USERS/SET-TOTAL-USERS-COUNT',
  TOGGLE_IS_FETCHING = 'SOCIAL_NETWORK/USERS/TOGGLE-IS-FETCHING',
  TOGGLE_IS_FOLLOWING_IN_PROGRESS = 'SOCIAL_NETWORK/USERS/TOGGLE-IS-FOLLOWING-IN-PROGRESS',
  SET_FILTER = 'SOCIAL_NETWORK/USERS/SET_FILTER',
}
