export enum ProfileReducerEnum {
  ADD_POST = 'SOCIAL_NETWORK/PROFILE/ADD_POST',
  DELETED_POST = 'SOCIAL_NETWORK/PROFILE/DELETED_POST',
  SET_USER_PROFILE = 'SOCIAL_NETWORK/PROFILE/SET-USER-PROFILE',
  SET_STATUS = 'SOCIAL_NETWORK/PROFILE/SET-STATUS',
  SAVE_PHOTO = 'SOCIAL_NETWORK/PROFILE/SAVE_PHOTO_SUCCESS',
}
