export enum NewsReducerEnum {
    ADD_NEWS = "SOCIAL_NETWORK/NEWS/ADD_POST",
    CHANGE_NEWS_TITLE = "SOCIAL_NETWORK/NEWS/CHANGE_NEWS_TITLE",
    CHANGE_NEWS_TEXT = "SOCIAL_NETWORK/NEWS/CHANGE_NEWS_TEXT",
    DELETE_NEWS = "SOCIAL_NETWORK/NEWS/DELETE_NEWS",
}